### ISSUE TITLE
Newspeak VMs do not open the Newspeak UI on Windows

### ISSUE THREAD

**Issue by fniephaus** [OpenSmalltalk/opensmalltalk-vm#151]
Citing @gbracha:
> I've tried the new spur VM that Fabio linked to, and its behavior is similar to the other windows nsvm builds on open smalltalk. It runs, but fails to open the Newspeak UI. More precisely, it will ask for an image (if you double-click on the VM instead of on an image directly) and then continue running. The task manager shows it as a background process. This would explain why the builds past any testing, as the background process seems to work.
I suspect something is amiss with the FFI. This probably broke between 2016.05.26 and 2016.06.30.

Here are the corresponding VMs:
https://bintray.com/opensmalltalk/vm/download_file?file_path=cog_win64x64_newspeak.cog.spur_201709050420.zip
https://bintray.com/opensmalltalk/vm/download_file?file_path=cog_win64x64_newspeak.stack.spur_201709050420.zip

@nicolas-cellier-aka-nice: would you have some time to look into this? VMs for other flavors don't seem to have this problem, otherwise we should have noticed and fixed it already.

**Comment by nicolas-cellier-aka-nice** [comment]
Is there a nsvm version known to work in either win32 or win64?

**Comment by nicolas-cellier-aka-nice** [comment]
Ah, it might also be a FFI Callback problem:
The FFICallbackThunk class in ns-2017-06-14.64.image is behind squeak trunk version.
The X64Win64 ABI is different from X64 SysV ABI, and thus Squeak trunk has a specific #initializeX64Win64 method which is missing in Newspeak. Could you upgrade the Newspeak image and retry?

**Comment by gbracha** [comment]
A quick update: I tried running an image with the fix suggested, but this does not solve the problem.

**Comment by fniephaus** [comment]
@nicolas-cellier-aka-nice: I believe @gbracha used [this version of `#initializeX64Win64`](https://github.com/pharo-project/pharo-core/blob/babfb83f16bba3cec23233edd32d2f481e863b55/Alien.package/FFICallbackThunk.class/instance/instance%20initalization/initializeX64Win64.st). Is it the right one? Any other ideas what we could do?

**Comment by nicolas-cellier-aka-nice** [comment]
The UI does not open, neither on 32bits nor 64bits VM, so this is probably not related to X64 ABI.
I put a break in ioShowDisplay with gdb and the VM is going there (via primitiveShowDisplayRect).
It is painting a region of a bitmap.
But since the window is not visible (hidden?) nothing seems to happen...

I'm not a specialist of windows UI, but there must be some obvious GUI call missing...
There should be a `ShowWindow(stWindow,SW_SHOW)` or something like that.

There is one in `ioForceDisplayUpdate()` but only `#if !NewspeakVM`.
It is suggested that Newspeak has to explicitely emit such request...
See https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/36270b33202975eee7adab9fa0905dd48421e1ef/platforms/win32/vm/sqWin32Window.c#L2263

I have checked the history of platforms/win32 around may/june 2016, not much happened there...
https://github.com/OpenSmalltalk/opensmalltalk-vm/commits/Cog?after=36270b33202975eee7adab9fa0905dd48421e1ef+244&path%5B%5D=platforms&path%5B%5D=win32&path%5B%5D=vm

**Comment by nicolas-cellier-aka-nice** [comment]
If I remove the guard at line 2263 and recompile the VM, I see the newspeak window appear...
So it looks like an essential call to `ShowWindow` is missing or failed (via FFI???).

**Comment by nicolas-cellier-aka-nice** [comment]
Ah Ah, but then I see a debugger with stack setupWindowProc...
Error Case not found PointerFFICallbackThunk...

This is in initializeStdCall: 
Though I took a recent ns-2020-03-02.64.image,
there is not case for Callback abi 'X64' as there should be...
(or not, X64 does not know about stdcall, there is a single ABI)

So, at least for 64 bits, there is an image side problem rather than a VM problem.

I suggest to amend line 2263 of sqWin32Window.c (#if 1) recompile, launch and debug newspeak, then return to regular VM.

**Comment by gbracha** [comment]
Had not noticed this before (I had given up on the issue long ago, I'm afraid). Will try and revisit. Thanks.
