### ISSUE TITLE
Fix all CI builds

### ISSUE THREAD

**Issue by fniephaus** [OpenSmalltalk/opensmalltalk-vm#172]
According to the [build history](https://travis-ci.org/OpenSmalltalk/opensmalltalk-vm/builds), it's been quite some time since all build passed.

**Comment by nicolas-cellier-aka-nice** [comment]
Continuous integration is quite useless with all this red

**Comment by fniephaus** [comment]
It is indeed. I was hoping we do "you break it, you fix it", but that didn't work apparently. We could force the Cog branch to always be green by only allowing changes that previously have been proven to pass, but then it takes longer to get things merged. Not sure if we want that...

**Comment by eliotmiranda** [comment]
Hi Fabio,

On Wed, Nov 15, 2017 at 11:47 AM, Fabio Niephaus <notifications@github.com>
wrote:

> It is indeed. I was hoping we do "you break it, you fix it", but that
> didn't work apparently. We could force the Cog branch to always be green by
> only allowing changes that previously have been proven to pass, but then it
> takes longer to get things merged. Not sure if we want that...
>

I'm trying to fix things but have pressing commitments.  I think I need to
start producing code to a different branch, Cogup comes to mind ;-).
What's the right way to roll back the Cog branch to before my cockup?

_,,,^..^,,,_
best, Eliot

**Comment by fniephaus** [comment]
No problem, we need to revert your bad commits then. Which commits need to be rolled back?

**Comment by fniephaus** [comment]
Builds are passing again: https://travis-ci.org/OpenSmalltalk/opensmalltalk-vm/builds/320227624.

**Comment by fniephaus** [comment]
It's true for Linux and macOS builds, but I just realized not so true for our Windows builds (e.g. [1]).
@estebanlm could you please have a look at the failing Pharo builds on AppVeyor?

[1] https://ci.appveyor.com/project/OpenSmalltalk/vm/build/1.0.856

**Comment by bencoman** [comment]
On 16 November 2017 at 04:19, Eliot Miranda <notifications@github.com>
wrote:

> Hi Fabio,
>
> On Wed, Nov 15, 2017 at 11:47 AM, Fabio Niephaus <notifications@github.com
> >
> wrote:
>
> > It is indeed. I was hoping we do "you break it, you fix it", but that
> > didn't work apparently. We could force the Cog branch to always be green
> by
> > only allowing changes that previously have been proven to pass, but then
> it
> > takes longer to get things merged. Not sure if we want that...
> >
>
> I'm trying to fix things but have pressing commitments. I think I need to
> start producing code to a different branch, Cogup comes to mind ;-).
>

Or consider trying a branch per feature to see lite-branches could fit your
workflow.

You'll want something to display the current branch in the shell prompt (if
you don't already).
I can't remember which one I used, but here are a few choices...
* https://gist.github.com/justintv/168835
* http://mediadoneright.com/content/ultimate-git-ps1-bash-prompt
* https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh

cheers -ben

**Comment by bencoman** [comment]
A side-comment from the peanut gallery...

On 16 November 2017 at 03:47, Fabio Niephaus <notifications@github.com>
wrote:

> It is indeed. I was hoping we do "you break it, you fix it", but that
> didn't work apparently.
>
Taking the path of least resistance is human nature.  There are varying
levels of "too busy to fix that right now."  Introducing the merge-barrier
shifts that balance point to encourage the idealistic behaviour of fixing
errors asap.

To mitigate concerns of delayed merges..
If these barriers sometimes get in the way of something critical, it should
be okay to temporarily disable them.  But at least the default encourages
the ideal behaviour and bypassing that require explicit action rather than
happening accidentally.

> We could force the Cog branch to always be green by only allowing changes
> that previously have been proven to pass, but then it takes longer to get
> things merged. Not sure if we want that...
>
Delayed merges are a fairly generic concern.  It would be good to expose
some detail from everyone concerned that enabling the following will
impeded their workflow...

https://help.github.com/assets/images/help/repository/protecting-branch-loose-status.png

That is...
What period of delay are you concerned about?
How often do you you think this would be a problem?
Is the problem the delay in merging-code, or the delay in getting the new
binary to run?

cheers -ben

**Comment by estebanlm** [comment]
heh… I have to say: I do not contribute to osvm other than PRs (never directly), so I always expect having a green build to merge. Also, I always have first a green build in my own build process (who builds all sources from scratch and tests the resulting VM executing all tests in Pharo), so when I do the PR, I tested my sources.
The problem we had with Pharo was because of two colliding issues (non related):

- server destination for deploy changed, and then keys became immediately wrong
- travis updated his server and didn’t included by default anymore libcurl for i386

this escapes the “you break it, you fix it” 

I agree no contribution should be accepted if it does not passes through a PR (and CI needs to pass), but that’s actually hard to do with current process: today VMMaker monticello is the “development branch” and you cannot prepare PRs with that… you need branch before generate sources, then commit into branch and then PR. I would recommend to use that approach but is more work than just commit so hard to adopt. 

Esteban

**Comment by bencoman** [comment]
On 27 December 2017 at 22:43, Esteban Lorenzano <notifications@github.com>
wrote:

> heh… I have to say: I do not contribute to osvm other than PRs (never
> directly), so I always expect having a green build to merge. Also, I always
> have first a green build in my own build process (who builds all sources
> from scratch and tests the resulting VM executing all tests in Pharo), so
> when I do the PR, I tested my sources.
> The problem we had with Pharo was because of two colliding issues (non
> related):
>
> - server destination for deploy changed, and then keys became immediately
> wrong


Sure, this is an anomaly that shouldn't occur too often. Its kind of an
act-of-god event.
But to remove such external dependency maybe each distribution's
"deployment"
could move to an isolated pipeline stage, so one distribution's deploy
infrastructure
can never affect the status of the build itself.
https://blog.travis-ci.com/2017-05-11-introducing-build-stages



> - travis updated his server and didn’t included by default anymore libcurl
> for i386


> this escapes the “you break it, you fix it”

I agree no contribution should be accepted if it does not passes through a
> PR (and CI needs to pass), but that’s actually hard to do with current
> process: today VMMaker monticello is the “development branch” and you
> cannot prepare PRs with that… you need branch before generate sources,


Actually you can create and change to a new branch after you generate
sources if you forget to do it before.
See accepted answer here...
https://stackoverflow.com/questions/2569459/git-create-a-branch-from-unstaged-uncommitted-changes-on-master



> then commit into branch and then PR. I would recommend to use that
> approach but is more work than just commit so hard to adopt.
>

If one routinely uses branch-per-feature then generating sources from
VMMaker is just another-feature in a familiar workflow.
It balances the distribution a small additional effort per integration
against the work to recover from the occasional slip getting into main
branch.

I guess the main difficulty is changing workflow habits.  In practice there
is some risk in changing workflows.
Anomalies can always pop up and its about finding the time to build
confidence in a new workflow.
btw, I think the community has gained a lot already in the move from svn to
git/github.
We'll get the next step sometime.

cheers -ben


> Esteban
>

**Comment by fniephaus** [comment]
Checkpoint: https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/31327d84196e279d2246ffc9033b061707901826 [[Travis](https://travis-ci.org/OpenSmalltalk/opensmalltalk-vm/builds/332898860)] [[AppVeyor](https://ci.appveyor.com/project/OpenSmalltalk/vm/build/1.0.948)]
