### ISSUE TITLE
Control keys broken on OS X

### ISSUE THREAD

**Issue by marceltaeumel** [OpenSmalltalk/opensmalltalk-vm#43]
VM: 201608171728
OS: OS X El Capitan 10.11.6
Keyboard: German

Here is how I observed the keyboard events in Squeak5.1rc1 (after filing in the attached files):

[KeyboardEvent-printOn.st.txt](https://github.com/OpenSmalltalk/opensmalltalk-vm/files/426696/KeyboardEvent-printOn.st.txt)
[KeyboardEvent-printKeyStringOn.st.txt](https://github.com/OpenSmalltalk/opensmalltalk-vm/files/426697/KeyboardEvent-printKeyStringOn.st.txt)

``` Smalltalk
| filter |
filter := PluggableEventFilter on: [:evt :target |
    Transcript showln: evt printString.
    evt].

Preferences disable: #duplicateControlAndAltKeys.
Preferences disable: #swapControlAndAltKeys.
Preferences disable: #duplicateAllControlAndAltKeys.

ActiveHand addKeyboardCaptureFilter: filter.

"After observation finished."
ActiveHand removeKeyboardCaptureFilter: filter.
Preferences enable: #duplicateAllControlAndAltKeys.
```

I observed the following bugs:
- Repeated key strokes are not working for [b..xB..X]. Not kidding.
- The values for keyDown and keyUp events are wrong. For example, hitting 'x' gives 7 for keyDown, 120 for keystroke, and 7 for keyUp. 120 is correct. Includes backspace, enter, etc.
- For the working keystrokes, there are way too many keyDown events when holding, for example, the letter 'x' key. I would expect a single keyDown, multiple keystroke, and after letting it go, a single keyUp. Since whe have keystroke events in the first place, there is no need for multiple keyDown (or a repeat field as in [SDL](https://wiki.libsdl.org/SDL_KeyboardEvent)).
- The values for keyDown and keyUp for arrow keys are wrong. The values for keystroke events are good. Adding modifiers such as CMD or SHIFT shows the same bug.
- No keyUp/down events for CTRL, SHIFT, CMD keys.
- The CTRL modifier in combination with other keys is **totally off**. CTRL+C gives a **single** keyUp with value 8 (backspace). CTRL+down gives keyDown 121 (y), keystroke 12 (page-down) and keyUp 9 (tab)

**Comment by codefrau** [comment]
Okay. There are some misunderstandings but also some actual bugs.
1. Key repeating: Not a bug. It has been disabled by Apple for all but editing keys. Pressing a key long pops up a little menu just like on iOS to choose umlauts etc (depends on keymap).
2.  keyDown and keyUp event codes: Not a bug. Key codes are _not_ the same between key stroke and key up/down events. Up/down are "raw" keycodes referring to the physical key. That means they should not change when you change the keyboard langugage (e.g. Z/Y when switching between German and English). On Mac VMs, they are the "Mac Virtual Key Codes" (see e.g. http://stackoverflow.com/questions/3202629/where-can-i-find-a-list-of-mac-virtual-key-codes). The Windows VM maps that to ASCII, but that is accidental and not in the API.
3. Too many keydowns: Not a bug. If a platform generates key repeats for non-characters (like F1) you only get keydown/up events, so the down should repeat, since there is no stroke. The multiple downs are easy to filter out in your application.
4. arrow keys: Not a bug. See 2.
5. No keydown/up for modifiers: Yes, that's a bug. Not a new bug though.
6. Ctrl-keys: Huge bug. This used to work in Carbon.  Here's what we used to get:

```
ctrl-a
#(2 448996 0 1 2 0 0 1)
#(2 448996 1 0 2 1 0 1)
#(2 449127 0 2 16 0 0 1)

ctrl-b
#(2 474124 11 1 2 0 0 1)
#(2 474124 2 0 2 2 0 1)
#(2 474211 11 2 16 0 0 1)

ctrl-c
#(2 38285 8 1 2 0 0 1)
#(2 38285 3 0 2 3 0 1)
#(2 38419 8 2 16 0 0 1)
```

That's almost correct, in the key-up event the modifier bit should be 2 not 16.
Now for Cocoa:

```
ctrl-a
#(2 534118 0 2 2 0 0 1) = keyup A + ctrl 

ctrl-b
#(2 568017 126 1 2 0 0 1) = keydown wtf
#(2 568017 30 0 2 30 0 1) = keystroke wtf
#(2 568105 11 2 2 0 0 1) = keyup B + ctrl

ctrl-c
#(2 441226 8 2 2 0 0 1) = keyup C + ctrl
```

So we at least get correct keyup events. But no down or stroke, or completely wacky down+stroke.

**Comment by marceltaeumel** [comment]
Well, if some of these issues are intentional on macOS, this is just tough luck. I described a coherent, forseeable behavior I would like to experience as a Smalltalk developer. Our goal should be to unify this behavior as much as possible for our supported operating systems. I do arguably prefer to see the VM fixed to support the behavior I previously described.

Simple. Consistent. Coherent. Unsurprising. 😄

I am not sure when the concept of a "key stroke" was introduced and who did it. There usually ([SDL](https://wiki.libsdl.org/SDL_KeyboardEvent), [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646267%28v=vs.85%29.aspx), [Apple](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/EventOverview/HandlingKeyEvents/HandlingKeyEvents.html)) seems "key up" and "key down" and a series of "key down" when the user holds the key. We, however, do have the concept of "key stroke". So there is no need to send multiple "key down" events. Just send multiple "key stroke" events.

If you want to implement a "hold long" feature, you could either add a "repeated?" flag to the key-stroke event or fully remove key-stroke events and just repeat key-down and have the flag "repeated?" there.

Either way, the "key code" **MUST** be the same for all kinds of keyboard events. Otherwise programming with these events becomes very challenging, which it already is. There are several scenarios where cannot use key-stroke events when only key-up and key-down can specify the desired behavior. For example, in a simple jump&run, the key-down starts the player movement and key-up ends it. It would be really challenging to implement a smooth movement with repeated key-stroke events. Now, the key codes in the key-up and key-down events must be cross-platform compatible. 

The VM has to abstract from platform specifics whenever possible. Here, it is definitely possible.

**Comment by codefrau** [comment]
Agreed. However, please do not conflate fixing bugs (restoring previous well-known behavior) with a redesign (changing the intended behavior).

A lot of the design issues are historical. At first there were only stroke events, we added down/up later. Initially there was only English (= ASCII), later we added Unicode support and special input methods, e.g. for Japanese.  It's not at all obvious how to generate characters (= strokes) from raw key presses (= keydowns) which is why we let the VM handle it, and we still have stroke events (or in X11 terminology, down/up are raw, stroke is cooked). E.g. the raw sequence `Alt down` `U down` `U up` `Alt up` `A down` `A up` should result in the cooked `ä` on a Mac if the `US International` keymap is active.

We have talked for many years about changing the keyboard event stuff, and to introduce cross-platform keycodes (the most promising idea was to use X11 keysyms on all platforms, because it supports the widest range of hardware). However, nowadays it should also take into account touch-screen keyboards, auto-correct etc. If you have a proposal, please open another ticket. For discussion, the mailing list is better.

In _this_ bug report we're concerned about the newly broken behavior. As far as I can tell, this only concerns the control key events, which is why I changed the title to reflect that. Also, this is straight-forward to fix. Agreeing on a new cross-platform design is not as straightforward.

**Comment by marceltaeumel** [comment]
Could you please extract the bugs into a new issue and restore the old title? Then we have two tickets with similar names to discuss improvements for the future.

**Comment by krono** [comment]
This should be  working now, can someone check?

**Comment by krono** [comment]
No complaints in nearly a year. close.
