### ISSUE TITLE
Feature Request: Add buildstamp to release assets

### ISSUE THREAD

**Issue by LinqLover** [OpenSmalltalk/opensmalltalk-vm#610]
My download folder looks pretty cluttered with names such as `squeak.cog.spur_win64x64 (3).zip`. I think it is a best practice to include the version/timestamp name of a build into the asset names. Could we maybe change the asset names to something like `osvm_202112201228_squeak.cog.spur_win64x64.zip`?

**Comment by LinqLover** [comment]
Maybe also in this format instead:

```
squeak.cog.spur_linux64x64_202101260417.tar.gz
```

(Seen in the [smalltalkCI releases](https://github.com/hpi-swa/smalltalkCI/releases/tag/v2.9.6))

**Comment by marceltaeumel** [comment]
If you rely on timestamps, fetch build artifacts from actions directly instead of the "latest-build" pre-release. We cannot include timestamps in the pre-release because we re-use it as stable links to the latest build. ;-) 

- https://github.com/OpenSmalltalk/opensmalltalk-vm/suites/7169716697/artifacts/285691320

I will close this comment because you can already get specific VM builds with a timestamp in the name.
