### ISSUE TITLE
unable to run the 202112201228 pre-release on mac os 12.3.1 (m1, monterey)

### ISSUE THREAD

**Issue by faried** [OpenSmalltalk/opensmalltalk-vm#624]
When I launch Squeak from `squeak.cog.spur_macos64ARMv8.dmg`, it crashes immediately and I get a popup asking me to move it to trash.  Right-clicking to "open" or launching it from outside the disk doesn't work either.  In dmesg's output I see

```
[37037.194729]: build_userspace_exit_reason: illegal flags passed from userspace (some masked off) 0x141, ns: 9, code 0x8
[37037.194799]: Waking up reference: 795Thread waiting on reference 795 woke upASP: Sleep interrupted, signal 0x100
[37037.194972]: ASP: Security policy would not allow process: 41283, /Volumes/squeak.cog.spur_macos64ARMv8/Squeak.app/Contents/MacOS/Squeak
```

I don't want to turn SIP off just for Squeak, and I don't know how to bypass this.

I've also tried the latest build from [here](https://github.com/OpenSmalltalk/opensmalltalk-vm/releases/download/latest-build/squeak.cog.spur_macos64ARMv8.dmg) (dated April 13 2022), and it runs into the same issue.

**Comment by krono** [comment]
Do not launch Squeak from the DMG.
Before doing anyhting, move it somewhere (but _not_ the Downloads folder)

**Comment by faried** [comment]
The first thing I did was copy it to `/Applications` before trying to launch it.  I've also tried copying it to other folders.

**Comment by krono** [comment]
Thanks for the info.
Maybe reelvant https://eclecticlight.co/2019/10/22/catalina-crashes-non-notarized-command-tools-with-a-quarantine-flag/

**Comment by faried** [comment]
That did the trick, thanks!

I'm surprised I've never run into that problem before.  Then again, my old laptop was upgraded from 10.14 to 12.3.1 over the years -- maybe sometime I set up early on worked around it.

**Comment by marceltaeumel** [comment]
Providing binaries outside the AppStore get trickier with every new macOS release.

Squeak bundles are signed, which enables you to open the .dmg but still requires and extra trick to confirm the start:
- http://files.squeak.org/trunk/Squeak6.0alpha-21585-64bit/Squeak6.0alpha-21585-64bit-202112201228-macOS-ARMv8.dmg

Thus we will also notarize the release bundles so that it works out of the box.

Note that if you build from the sources yourself, those restrictions do not apply. You can just run the VM through .app or binary.
