### ISSUE TITLE
Using system defined JPEG library for OpenSmalltalk

### ISSUE THREAD

**Issue by cstes** [OpenSmalltalk/opensmalltalk-vm#695]
The OpenSmalltalk vm is currently at version VMMaker.oscog-eem.3424 in the OpenIndiana UNIX repository.

The https://docs.openindiana.org/handbook/community/squeak/ handbook gives more info on this.

I would like to use  the system provided JPEG library for building the JPEG plugin for OpenSmalltalk (and preferably as an external plugin) but I think by default JPEG is using an internal plugin withan old version of what I think is libjpeg6.

In the classical Squeak VM (which is built from subversion) there was work to use the system provided JPEG and I think the request to do so, came from Debian Linux, who have the same concern as the OpenIndiana developers.

For OpenIndiana packages are requested to use libjpeg8-turbo instead of the old libjpeg6 but as far as I can see for OpenSmalltalk, the JPEG support is pretty much hardcoded in the VM.

So I would like to either simply drop (remove) the JPEG plugin which seems acceptable to me (I don't think a lot of Smalltalk applications really requires the JPEG code ?) or have some way to use a system provided JPEG library.

**Comment by eliotmiranda** [comment]
Hi David,On Aug 19, 2024, at 9:10 AM, David Stes ***@***.***> wrote:﻿
The OpenSmalltalk vm is currently at version VMMaker.oscog-eem.3424 in the OpenIndiana UNIX repository.
The https://docs.openindiana.org/handbook/community/squeak/ handbook gives more info on this.
I would like to use  the system provided JPEG library for building the JPEG plugin for OpenSmalltalk (and preferably as an external plugin) but I think by default JPEG is using an internal plugin withan old version of what I think is libjpeg6.
In the classical Squeak VM (which is built from subversion) there was work to use the system provided JPEG and I think the request to do so, came from Debian Linux, who have the same concern as the OpenIndiana developers.
For OpenIndiana packages are requested to use libjpeg8-turbo instead of the old libjpeg6 but as far as I can see for OpenSmalltalk, the JPEG support is pretty much hardcoded in the VM.
So I would like to either simply drop (remove) the JPEG plugin which seems acceptable to me (I don't think a lot of Smalltalk applications really requires the JPEG code ?) or have some way to use a system provided JPEG library.It would be great to upgrade the plugin to use a more up-to-date version of the plugin. Do you have cycles to put into that effort? I can help you with VMMaker.  I don’t have time right now but by next week things should open up a little_,,,^..^,,,_ (phone)

**Comment by jvuletich** [comment]
There is indeed "a lot" of Smalltalk code assuming the support for JPEG is provided by the VM. Speaking as the original author of JPEGReadWriter2Plugin and the lead dev of Cuis. An updated JPEG plugin would be nice, although if the primitives provided by JPEGReadWriter2Plugin need to change, 1) the impact on existing Squeak / Cuis / Pharo images needs to be acknowledged and accepted by the communities, and 2) we need to understand how to adapt current releases of Cuis and Squeak to use the new API.

**Comment by marceltaeumel** [comment]
A JPEGReadWriter**3**Plugin would probably the way to go then. Copy over what is still beneficial, make changes without breaking existing code. Retire v2 later if necessary. Even now, we can switch back to the Smalltalk-only v1 if necessary. But it is much slower. 😄

**Comment by krono** [comment]
Note that we got the squeak-vm expelled from debian — among other things — because we shipped (aka "vendored") an outdated, vulnerable verison of libjepg ourselves…

**Comment by jvuletich** [comment]
> A JPEGReadWriter**3**Plugin would probably the way to go then. Copy over what is still beneficial, make changes without breaking existing code. Retire v2 later if necessary. Even now, we can switch back to the Smalltalk-only v1 if necessary. But it is much slower. 😄

I agree with everything except the "Smalltalk-only v1". I believe that code could only decode, not encode jpeg, if I remember correctly.

**Comment by dtlewis290** [comment]
In our (unfortunately incomplete) effort to address the Debian concerns, we did not get as far as addressing it here in opensmalltalk-vm, but for the classic squeakvm we baked something into the CMake build procedures. The SVN commit notice is below, but I'll have to check and make sure it still works on newer Linux because I have not tried it recently. Assuming that it does still work, it should be possible to do something similar here.

r3806 | lewis | 2021-07-08 18:46:59 -0400 (Thu, 08 Jul 2021) | 7 lines

Debian distro support.
Add --link-shared-lib option to the platforms/unix/configure script. If
specified, use dynamic linking to platform -ljpeg and -lpcre, otherwise
use default behavior of linking to the old but stable code in platforms
directory. Debian distro maintainers can now specify --link-shared-lib
to enforce dynamic linking to the system libraries.

**Comment by cstes** [comment]
When I opened this issue, the difference between the plugin JPEGReaderPlugin and JPEGReadWriter2Plugin was not clear to me.  I had read squeak's wiki 4043 which gives an example with Quartz Brezil.jpg file to open it with JPEGReadWriter2 formFromFile:'some.jpg' asMorph openInHand.

After some testing, I disabled JPEGReadWriter2Plugin in my plugins.int file for the OpenIndiana build (specifically only there).   This only affects the build in OpenIndiana and has no result at all in the opensmalltalk-vm sources.

I tested after publishing the cog-spur 3424 and stack-spur 3423 that after disabling the JPEGReadWriter2Plugin ,  I still seem to be able to open JPEG images using the JPEGReadWriter formFromFile:'some.jpg' asMorph openInHand.  

Perhaps the wiki 4043 (https://wiki.squeak.org/squeak/4043) could be updated to provide an example with the JPEGReadWriter  class as opposed to JPEGReadWriter2.

I am closing this github issue because for the moment this resolves the issue for me :  in the openindiana package JPEGReadWriter2Plugin  is disabled and JPEGReaderPlugin  is left enabled, and it is still possible to open JPEG files.

If any OpenIndiana cog-spur or stack-spur user would prefer so, that user can still build / compile their own VM with the JPEGReadWriter2Plugin   enabled.

For tests I used Cuis7.1 update 6456 (works fine on OpenIndiana using stack-spur 3423 or cog-spur 3424 (compiled with GCC 13.3) and I also tested with Squeak6.1 alpha # 23091 SistaV1 64bit image 68533 format  .

In the future I would like to set up my own VMMaker environment (this is documented in a wiki by David Lewis, wiki 6177 ) and if I find time I am willing to try to work on an update of the JPEGReadWriter2Plugin   or JPEGReadWriter3Plugin, but for the moment the OpenIndiana specific issue is resolved.

I simply disable any specific plugin that could be problematic, while the OpenSmalltalk VM package as a whole remains perfectly useful and is even able to open JPEG files without using the system defined C level library.
