### ISSUE TITLE
Add tests that check the VM can run, not just build

### ISSUE THREAD

**Issue by rmacnak** [OpenSmalltalk/opensmalltalk-vm#86]
The current Travis and Appveyor jobs merely test that the VM can build. They should also run the Squeak or Pharo test suite or Newspeak bootstrap depending on flavor.  Even just ignore the test results and merely checking the test suite can complete without crashing would be a huge improvement in coverage.

**Comment by fniephaus** [comment]
I've looked into making the Newspeak bootstrap process part of corresponding builds.
Unfortunately, [it fails at the moment](https://travis-ci.org/fniephaus/vm/jobs/172226635) for a reason that I don't understand (yet), but I've heard that there is at least one issue with the latest VMs and Newspeak anyway.
Also, the 64bit version of Newspeak [doesn't run](https://travis-ci.org/fniephaus/vm/jobs/172226633) on `macos64x64` because it seems incompatible.
Additionally, we need to find a way to run VMs that use a threaded heartbeat on Linux/Travis...

**Comment by rmacnak** [comment]
Thanks for looking into this!

The 32-bit failure is because the bootstrap requires both the 'nsboot' and 'newspeak' repositories as sibling directories. That build is missing the 'newspeak' repository and so missing all Newspeak sources.

The 64-bit failure is because one must use 'build64.sh' instead of 'build32.sh'. Unfortunately, Cog has separate image formats for 32-bit and 64-bit VMs. The two scripts differ in choosing what Squeak 5.1 image to start from.

**Comment by fniephaus** [comment]
Ah thanks! The build cloned the Newspeak repository but the directory name was actually different.
I am using `build64bit.sh` but the image header is different (`68019` vs `68021`).

BTW: I have managed to run threaded heartbeat VMs on TravisCI :)

**Comment by fniephaus** [comment]
[Check this out](https://travis-ci.org/fniephaus/vm/jobs/172329298) :)

**Comment by rmacnak** [comment]
That's it!  Also it's nice to learn one can use ulimit to give threaded heartbeat VMs permission without needing to relog.

**Comment by fniephaus** [comment]
Ok, so I go [the `macos32x86` build working](https://travis-ci.org/fniephaus/vm/jobs/172886672), but I'm still having problems with the `linux32x86` build and the 64bit builds:

The `linux32x86` build [fails because it can't find `libc.so.6`](https://travis-ci.org/fniephaus/vm/jobs/172886670#L1778), even though [`libc6-i386` is installed](https://travis-ci.org/fniephaus/vm/jobs/172886670#L181).

The 64bit builds fail because the image can't be opened:

> [This interpreter (vers. 68021) cannot read image file (vers. 68019).](https://travis-ci.org/fniephaus/vm/jobs/172886671#L2296)

Any idea what to do to get it working?

**Comment by rmacnak** [comment]
The libc issue is probably because you're invoking `lib/nsvm/5.0-201611030953/nsvm` instead of `bin/nsvm`. The latter is a shell script that sets up `LD_LIBRARY_PATH`. Though I don't understand why that should be necessary.

**Comment by rmacnak** [comment]
Newspeak tests added in 9c6752de414800272e9040840490a8a364c7e4da.  Leaving this issue open for Squeak tests.

**Comment by fniephaus** [comment]
Thanks. I will add SUnit testing for Squeak and Pharo next week. And I'll keep @estebanlm posted as he works on merging the Pharo-vm.

**Comment by fniephaus** [comment]
Closed with https://github.com/OpenSmalltalk/opensmalltalk-vm/pull/90.
